"""add chunk_meta and vec_chunks

Revision ID: f3a6512d59c3
Revises: b1d6fdf7901a
Create Date: 2026-06-20 13:56:26.054503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a6512d59c3'
down_revision: Union[str, Sequence[str], None] = 'b1d6fdf7901a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'chunk_index', name='uq_chunk_chapter_index')
    )
    with op.batch_alter_table('chunk_meta', schema=None) as batch_op:
        batch_op.create_index('idx_chunk_chapter', ['chapter_id'], unique=False)

    # M3b: vec_chunks virtual table (sqlite-vec). SQLAlchemy can't autogenerate this.
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS vec_chunks USING vec0("
        "embedding FLOAT[1024])"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS vec_chunks")

    with op.batch_alter_table('chunk_meta', schema=None) as batch_op:
        batch_op.drop_index('idx_chunk_chapter')

    op.drop_table('chunk_meta')
    # ### end Alembic commands ###
